use customer_behavior

select TOP 20 * from customer

-- Q 1 What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount_usd) as revenue
from customer
group by gender

-- Q 2 Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount_usd
from customer
where discount_applied= 'Yes' and purchase_amount_usd>= (select AVG(purchase_amount_usd) from customer)

-- Q 3 Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

-- Q 4 Compare the average purchase amounts between Standard and Express Shipping.
SELECT 
    shipping_type,
    ROUND(AVG(CAST(purchase_amount_usd AS FLOAT)), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q 5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(AVG(cast(purchase_amount_usd as float)),2) as avg_spend,
round(sum(cast(purchase_amount_usd as float)),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q 6 Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
round(100.0* sum(case when discount_applied= 'Yes' then 1 else 0 end)/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc

-- Q7 Segment customers into New, Returning, and Loyal

WITH customer_type AS
(
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases <= 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment
ORDER BY Number_of_Customers DESC;

-- Q 8 What are the top 3 most purchased products within each category?
with item_counts as (
select category, 
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3


-- Q 9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

-- Q 10 What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount_usd) as total_revenue
from customer
group by age_group
order by total_revenue desc;